FROM jenkins/jenkins:lts

USER root

# Installer Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Ajouter jenkins au groupe docker
RUN groupadd docker || true && usermod -aG docker jenkins

USER jenkins
